### PR TITLE
Add on for Firefox of Gmail Labels as Tabs

### PR DESCRIPTION
**Pull request by jespicas**
This is first step to work with Firefox add-on
Now add on is recognized by Firefox but needs to fix some differences with Browsers
I think this is first iteration. Can you see screenshot
Screenshot from 2020-10-03 20-31-52

### CODE REVIEW

**Comment by tuladhar** [comment]
Looks good @jespicas.

It'd be great, If you can create a TODO list, so we can then create issues for those to be worked on independently.

**Comment by jespicas** [comment]
> Looks good @jespicas.
> 
> It'd be great, If you can create a TODO list, so we can then create issues for those to be worked on independently.

Where do you prefear add a TODO List, creating Tasks in the Projects Tab of the repo ? or simply add a list in this PR ?

**Comment by tuladhar** [comment]
@jespicas GitHub Projects seems like a better option. I have created a project [Firefox Extension: Gmail Labels as Tabs](https://github.com/tuladhar/gmail-labels-as-tabs/projects/1). Let's add in there.

**Comment by jespicas** [comment]
@tuladhar  I can't add anything in the project, may I'm not still a contributor ?

**Comment by tuladhar** [comment]
Looks like it. I've invited you as contributors. Please accept.

**Comment by jespicas** [comment]
> Looks like it. I've invited you as contributors. Please accept.

Accepted!

**Comment by jespicas** [comment]
> Looks like it. I've invited you as contributors. Please accept.

You agree to merge this PR ?

**Comment by tuladhar** [comment]
Yeah, looks good for the first pass. Merging it!

**Pull request merged**
